### ISSUE TITLE
Very confused about usage

### ISSUE THREAD

**Issue by dlo** [olddonkey/ODUIThreadGuard#14]
The README says there's "no need to import any files, it is a extension of UIView, so it will work automatically" but then in a later paragraph it seems you need to drag a file into your project to use it? Unclear how to get this working. Dragging and dropping a file into one's project sort of nullifies the point of using Cocoapods. :)

**Comment by olddonkey** [comment]
You are right, that's why I don't recommend you use this anymore, as in Xcode9, Apple provides main thread checker, and enabled by default,  so use that should be enough

**Comment by dlo** [comment]
Thanks!
