### ISSUE TITLE
使用时机 Help wanted

### ISSUE THREAD

**Issue by Beyond-Chao** [olddonkey/ODUIThreadGuard#16]
/// It is better to use a debug flag here for not add this extension to Release build. (You don't want user see App crash)
这句注释有点歧义，不应该在Release版本打开，为什么这样？

我的理解是 在Debug版本去掉，Release打开，把问题尽量暴露在测试开发阶段，上线之后打开，多一层保护，防止异常。

**Comment by olddonkey** [comment]
你好，抱歉这么晚才回复，因为这个guard的目的是在开发的阶段尽早的发现问题，所以我选择了在开发过程中如果遇到从后台线程对UI进行改变的情况，直接assert掉进程，同时可以throw出内存堆栈，这样的话可以比较直观的发现问题。如果在release中打开的话，一旦有代码写错，直接会导致app被kill掉

你的思路是颠倒过来，如果在运行过程中发现如果不是在主线程中，那dispatch到主线程里，我也考虑过那样的情况，但是最大的问题是在做method swizzling 的过程中会有性能损失，所以个人感觉不是很合适。
