### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by ashavit** [olddonkey/ODUIThreadGuard#2]
Please add a TL;DR section on the Readme for quick understanding on how this is to be implemented (after cocoa pods of course)
thanx.

**Comment by Morkrom** [comment]
- Passive implementation
- Throw an assertion if setNeedsDisplay, setNeedsLayout, or setNeedsDisplayInRect: is called for instantion of any UIView

**Comment by olddonkey** [comment]
Thanks guys for the help, forgive my poor english
